CREATE TABLE IPL_BATTING AS 
SELECT PLAYER_NAME AS PLAYER , SR AS STRIKE_RATE
FROM(
SELECT  PLAYER_NAME,ROUND(AVG(STRIKE_RATE),2) AS SR 
FROM IPL_BAT
GROUP BY PLAYER_NAME
ORDER BY SR DESC)


CREATE TABLE IPL_BOWLING AS 
SELECT PLAYER_NAME AS PLAYER , ECONOMY
FROM(
SELECT  PLAYER_NAME,ROUND(AVG(ECONOMY),2) AS ECONOMY 
FROM IPL_BOWL
GROUP BY PLAYER_NAME
ORDER BY ECONOMY)

DELETE FROM IPL_BATTING
WHERE PLAYER IS NULL 
   OR STRIKE_RATE IS NULL
   
   
SELECT * FROM IPL_BATTING

UPDATE IPL_2025
SET PLAYERS = 'VIRAT KOHLI'
WHERE TRIM(PLAYERS) = 'V KOHLI';

ALTER TABLE IPL_BATTING
DROP COLUMN VALUE_POINT


CREATE TABLE IPL_TEAMS AS
SELECT TEAM_NAME ,PLAYERS , VALUE_POINT
FROM(
SELECT 
    t.TEAM_NAME,
    t.PLAYERS,   
    COALESCE(b.Value_Point, 0) AS Value_Point  
FROM IPL_2025 t
LEFT JOIN POINT_TABLE b ON TRIM(t.PLAYERS) = TRIM(b.PLAYER) 
ORDER BY t.TEAM_NAME DESC);

SELECT TEAM_NAME , SUM(VALUE_POINT) AS POINTS 
FROM IPL_TEAMS
GROUP BY TEAM_NAME

select * from IPL_TEAMS
select * from IPL_BATTING_
select * from IPL_BOWLING_
select * from IPL_BATTING

SELECT * FROM POINT_TABLE
 
DROP TABLE IPL_BOWLING_
select * from POINT_TABLE


CREATE TABLE POINT_TABLE AS
SELECT PLAYER , VALUE_POINT FROM (
SELECT 
    PLAYER, 
    SUM(Value_point) AS Value_point  
FROM (
    SELECT PLAYER, Value_point FROM IPL_BATTING_
    UNION ALL  
    SELECT PLAYER, Value_point FROM IPL_BOWLING_
)combined
GROUP BY PLAYER )  


// FINAL POINT TABLE WITH CORRECT DATA

SELECT PLAYER, MAX(Value_Point) AS Value_Point
FROM (
    SELECT PLAYER, Value_Point FROM IPL_BATTING_
    UNION ALL
    SELECT PLAYER, Value_Point FROM IPL_BOWLING_
) Combined
GROUP BY PLAYER
ORDER BY Value_Point DESC;


